-- Tienda
USE tienda; SELECT nombre FROM producto;
USE tienda; SELECT nombre, precio FROM producto;
USE tienda; SELECT * FROM producto;
USE tienda; SELECT nombre, precio '€', precio * 1.13 '$' FROM producto;
USE tienda; SELECT nombre AS 'nom de producto', precio AS euros, precio * 1.13 AS dolars FROM producto;
USE tienda; SELECT UPPER(nombre), precio FROM producto;
USE tienda; SELECT LOWER(nombre), precio FROM producto;
USE tienda; SELECT nombre, upper(substring(nombre,1,2)) as InicialesMayusculas FROM producto;
USE tienda; SELECT nombre, ROUND(precio,2) FROM producto;
USE tienda; SELECT nombre, TRUNCATE(precio,0) as PrecioSinDecimal FROM producto;
USE tienda; SELECT codigo_fabricante FROM producto;
USE tienda; SELECT codigo FROM producto GROUP BY codigo_fabricante;
USE tienda; SELECT nombre FROM fabricante ORDER BY nombre ASC;
USE tienda; SELECT nombre FROM fabricante ORDER BY nombre DESC;
USE tienda; SELECT nombre, precio FROM producto ORDER BY nombre ASC,precio DESC;
USE tienda; SELECT * FROM fabricante ORDER BY codigo ASC LIMIT 5;
USE tienda; SELECT * FROM fabricante ORDER BY codigo ASC LIMIT 3,2;
USE tienda; SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
USE tienda; SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
USE tienda; SELECT nombre, codigo_fabricante FROM producto where codigo_fabricante = 2;
USE tienda; SELECT p.nombre, p.precio, f.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante=f.codigo;
USE tienda; SELECT f.nombre, p.nombre, p.precio  FROM producto p, fabricante f WHERE p.codigo_fabricante=f.codigo ORDER BY f.nombre ASC;
USE tienda; SELECT p.codigo, p.nombre, f.codigo, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante;
USE tienda; SELECT p.nombre, MIN(p.precio), f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante;
USE tienda; SELECT p.nombre, MAX(p.precio), f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante;
USE tienda; SELECT p.nombre, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND f.nombre LIKE 'lenovo';
USE tienda; SELECT p.nombre, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND f.nombre LIKE 'crucial' and p.precio > 200;
USE tienda; SELECT p.nombre, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND f.nombre REGEXP 'asus|hew|sea';
USE tienda; SELECT p.nombre, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND f.nombre IN ('asus','hewlett-packard','seagate');
USE tienda; SELECT p.nombre, p.precio, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND f.nombre REGEXP 'e$';
USE tienda; SELECT p.nombre, p.precio, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND f.nombre REGEXP 'w';
USE tienda; SELECT p.nombre, p.precio, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND p.precio >= 180 ORDER BY p.precio DESC, f.nombre ASC;
USE tienda; SELECT f.codigo, f.nombre FROM fabricante f, producto p WHERE f.codigo=p.codigo_fabricante GROUP BY f.codigo;
USE tienda; SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo=p.codigo_fabricante;
USE tienda; SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo=p.codigo_fabricante where p.nombre IS NULL;
USE tienda; SELECT p.nombre, f.nombre  FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante AND f.nombre LIKE 'lenovo';
USE tienda; SELECT p.codigo, p.nombre, p.precio, p.codigo_fabricante FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante and p.precio =(SELECT max(pp.precio) from producto pp, fabricante fp where fp.codigo=pp.codigo_fabricante and fp.nombre like'lenovo');
USE tienda; SELECT p.nombre, max(p.precio)  FROM producto p, fabricante f WHERE  f.codigo=p.codigo_fabricante AND f.nombre LIKE 'lenovo';
USE tienda; SELECT p.nombre, min(p.precio)  FROM producto p, fabricante f WHERE  f.codigo=p.codigo_fabricante AND f.nombre LIKE '%hew%';
USE tienda; SELECT p.nombre FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante and p.precio >=(SELECT max(pp.precio) from producto pp, fabricante fp where fp.codigo=pp.codigo_fabricante and fp.nombre like'lenovo');
USE tienda; SELECT p.nombre FROM producto p, fabricante f WHERE f.codigo=p.codigo_fabricante and f.nombre like 'asus' and p.precio > (SELECT AVG(pp.precio) from producto pp, fabricante fp where fp.codigo=pp.codigo_fabricante and fp.nombre like'asus');
-- Universitat
USE universidad; SELECT p.apellido1, p.apellido2, p.nombre FROM persona p ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
USE universidad; SELECT p.nombre, p.apellido1, p.apellido2, p.telefono FROM persona p where telefono IS NULL;
USE universidad; SELECT * FROM persona p where fecha_nacimiento LIKE '%1999%';
USE universidad; SELECT * FROM persona p where tipo = 'profesor' AND telefono IS NULL AND nif REGEXP'K$';
USE universidad; SELECT * FROM asignatura a WHERE cuatrimestre=1 AND curso =3 AND id_grado=7;
USE universidad; SELECT p.apellido1, p.apellido2, p.nombre, d.nombre FROM profesor pr  INNER JOIN departamento d ON d.id=pr.id_departamento INNER JOIN persona p ON p.id=pr.id_profesor ORDER BY p.apellido1 ASC, p.nombre ASC;
USE universidad; SELECT a.nombre, ce.anyo_inicio, ce.anyo_fin FROM persona p INNER JOIN alumno_se_matricula_asignatura asma ON p.id=asma.id_alumno INNER JOIN asignatura a ON asma.id_asignatura=a.id INNER JOIN curso_escolar ce ON a.curso=ce.id WHERE p.nif ='26902806M';
USE universidad; SELECT d.nombre FROM  departamento d INNER JOIN profesor pr ON d.id=pr.id_departamento INNER JOIN asignatura a ON a.id_profesor=pr.id_profesor INNER JOIN grado g ON g.id=a.id_grado GROUP BY d.nombre;
USE universidad; SELECT p.nombre,p.apellido1,p.apellido2 FROM  persona p INNER JOIN alumno_se_matricula_asignatura asma ON p.id=asma.id_alumno INNER JOIN curso_escolar ce ON asma.id_curso_escolar=ce.id WHERE ce.anyo_inicio=2018 AND ce.anyo_fin=2019 GROUP BY p.id;
-- LEFT JOIN / RIGHT JOIN
USE universidad; SELECT d.nombre,p.apellido1,p.apellido2,p.nombre FROM departamento d LEFT JOIN profesor pr ON d.id=pr.id_departamento LEFT JOIN persona p ON pr.id_profesor=p.id ORDER BY d.nombre ASC , p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
USE universidad; SELECT*FROM profesor pr  LEFT JOIN departamento d ON pr.id_departamento = d.id WHERE d.id IS NULL;
USE universidad; SELECT*FROM departamento d LEFT JOIN profesor pr ON d.id=pr.id_departamento WHERE pr.id_departamento IS NULL;
USE universidad; SELECT p.nombre, p.apellido1, p.apellido2, a.nombre AS asignatura FROM profesor pr LEFT JOIN asignatura a ON pr.id_profesor=a.id_profesor LEFT JOIN persona p ON pr.id_profesor=p.id WHERE a.id_profesor IS NULL;
USE universidad; SELECT a.nombre AS NombreAsignatura, p.nombre AS ProfesorAsignado FROM asignatura a  LEFT JOIN persona p ON a.id_profesor = p.id WHERE id_profesor IS NULL;
USE universidad; SELECT*FROM departamento d LEFT JOIN profesor pr ON d.id=pr.id_departamento LEFT JOIN asignatura a ON a.id_profesor=pr.id_profesor WHERE a.curso IS NULL;
-- Resum
USE universidad; SELECT COUNT(p.id) AS NumeroDeAlumnos FROM persona p WHERE tipo LIKE 'alumno';
USE universidad; SELECT COUNT(p.id) AS NumeroDeAlumnos FROM persona p WHERE tipo LIKE 'alumno' AND fecha_nacimiento LIKE'%1999%';